name: deploying to gh-pages
on:
  push:
    branches:
     - "matser"


job:
  # create the jobs
  name: Build and Test
  runs-on: ubuntu_latest

  strategy:
    matrix:
      node-version: [14]

  steps:
       -name: Checkout
       uses: actions/checkout@v1


    -name: Install dependencies
    run: npm ci
    
    -name: Build
    run: npm run build:ci

    #Upload Artifacts
    -name: Archive build
    if: success()
    uses: actions/upload-artifact@v1
    with: 
      name: deploy_dist
      path: dist
    -name: Archive code coverage result
    if: success()
    uses: actions/upload-artifact@v1
    with:
      name: deploy_coverage
      path: coverage

    #Create deploy job
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        -name: Checkout
        uses: actions/checkout@v1
        -name: Download Build
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
         -name: Deploy to Github Pages
         uses: JamesIves/github

    